src/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests/CommandLineTests.cs

Added a few more tests
- create queue
- delete queue
- create queue when it already exists

Additional tests

---

src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Bump ASB client to use stable version

---

src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Add net461 target

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

This updates development tooling on the `master` branch.
Note: This should not be squashed.

Master Update testing packages

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

This updates development tooling on the `develop` branch.
Note: It is okay for this to be squashed.

Update development tooling

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

@Particular/azure-maintainers please review/merge.

Update test projects to use ASB client to 3.3.0

---

src/AcceptanceTests/Sending/When_using_dispatcher_directly_within_transactionscope_and_conflicting_isolation_level.cs
src/Transport/Sending/MessageDispatcher.cs

Suppress scope when DispatchConsistency is Default and Send-Via is not used

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/Administration/NamespacePermissions.cs
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Release 1.0.1

---

src/Transport/Sending/OutgoingMessageExtensions.cs

Related to https://github.com/Particular/NServiceBus.Azure/issues/106

Set Message.ContentType from custom header NServiceBus.ContentType

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Bump ASB client to 3.4.0

---

.github/CODEOWNERS
src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/Configuration/AzureServiceBusTransportSettingsExtensions.cs
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/Transport/Sending/OutgoingMessageExtensions.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Release 1.1.0

---

src/Transport/Receiving/MessagePump.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Hotfix 1.1.1

---

src/Transport/Receiving/MessagePump.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Hotfix 1.0.2

---

src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/Receiving/MessagePump.cs

Fixes #63 (PrefetchCount set to zero does not disable prefetching).

Fix MessagePump to take into consideration prefetch count set to zero

---

src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/Receiving/MessagePump.cs

Backport of the fix for #63 (PrefetchCount set to zero does not disable prefetching).

PrefetchCount set to zero does not disable prefetching

---

src/Transport/Receiving/MessagePump.cs
src/TransportTests/When_MessageLockLostException_is_thrown.cs
src/TransportTests/When_ServiceBusTimeoutException_is_thrown.cs

Do not raise critical error for MessageLockLostException

---

src/Transport/Receiving/MessagePump.cs

No continuation style, fixes #31

---

src/CommandLine/Endpoint.cs

Include more details in global tool for queue, topic, subscription or rule creation, closes #30

---

src/Tests/Sending/MessageSenderPoolTests.cs
src/Transport/Sending/MessageSenderPool.cs

Fix returning of senders to pool to avoid creating unnecessary senders

---

src/Tests/Sending/MessageSenderPoolTests.cs
src/Transport/Sending/MessageSenderPool.cs

Backport of #88 for release-1.3 branch

MessageSenders are not correctly returned to pool leading to QuotaExceededException

---

GitVersion.yml
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Update Particular.Packaging in release-1.4

---

GitVersion.yml
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Update Particular.Packaging in release-1.2

---

GitVersion.yml
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Update Particular.Packaging in master

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in master

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in release-1.4

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in release-1.3

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in release-1.2

---

src/Transport/Administration/QueueCreator.cs
src/Transport/Administration/SubscriptionManager.cs

Found this while spelunking in the code

Always close the management client

---

src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Transport/Administration/QueueCreator.cs
src/Transport/Administration/SubscriptionManager.cs
src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/Configuration/AzureServiceBusTransportSettingsExtensions.cs
src/Transport/Configuration/SettingsKeys.cs
src/Transport/FodyWeavers.xml
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/Transport/obsoletes-v2.cs
src/TransportTests/ConfigureAzureServiceBusTransportInfrastructure.cs

Subscription and rule convention API

---

src/Transport/Receiving/MessagePump.cs

so the stack trace can be logged
https://discuss.particular.net/t/support-for-net-5/2227

pass missing exception

---

src/Transport/Receiving/MessagePump.cs

local PR for https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/219

pass exception to logger

---

src/AcceptanceTests/.editorconfig
src/CommandLine/.editorconfig
src/CommandLine/GlobalSuppressions.cs
src/CommandLineTests/.editorconfig
src/Tests/.editorconfig
src/TransportTests/.editorconfig

Drop missed file

---

src/Transport/AzureServiceBusTransport.cs
src/Transport/AzureServiceBusTransportInfrastructure.cs

Previously, queues were always created, regardless of the host settings `SetupInfrastructure` flag

Do not always create queues

---

src/Transport/NServiceBus.Transport.AzureServiceBus.csproj

Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482

upgrade target framework

---

src/CommandLine/Endpoint.cs
src/CommandLine/Program.cs
src/CommandLineTests/CommandLineTests.cs
src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Tests/Testing/TestableCustomizeNativeMessageExtensionsTests.cs
src/Transport/Receiving/MessagePump.cs
src/Transport/Sending/CustomizeNativeMessageExtensions.cs
src/Transport/Testing/TestableCustomizeNativeMessageExtensions.cs

Includes
- #254 
- #259 
- #222 
@aleksandr-samila and I had to reimplement the testing functionality of #259 to be compatible with the two extension methods (one for the session and one for the context)

Bring back the necessary changes to 1.9.0

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_using_dispatcher_directly_within_transactionscope_and_conflicting_isolation_level.cs
src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/Administration/SubscriptionManager.cs
src/Transport/AzureServiceBusTransport.cs
src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/Transport/Receiving/MessagePump.cs
src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
src/Transport/Sending/MessageDispatcher.cs
src/TransportTests/ConfigureAzureServiceBusTransportInfrastructure.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
src/TransportTests/When_MessageLockLostException_is_thrown.cs
src/TransportTests/When_ServiceBusTimeoutException_is_thrown.cs

Primarily adding the additional `CancellationToken` arguments to the implementations. The usage of the parameter token must not be considered as correct it was agreed with the CTS TF that we will just make the code compile.
cc @andreasohlund

Update ASB to NServiceBus Core 852

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_using_dispatcher_directly_within_transactionscope_and_conflicting_isolation_level.cs
src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Tests/MigrationApiTests.cs
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/Administration/SubscriptionManager.cs
src/Transport/AzureServiceBusTransport.cs
src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/Transport/Receiving/MessagePump.cs
src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
src/Transport/Sending/MessageDispatcher.cs
src/TransportTests/ConfigureAzureServiceBusTransportInfrastructure.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
src/TransportTests/When_MessageLockLostException_is_thrown.cs
src/TransportTests/When_ServiceBusTimeoutException_is_thrown.cs

relates to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/275

fixup token support

---

src/AcceptanceTests/Receiving/When_receiving_a_message_from_legacy_asb.cs
src/Transport/Receiving/MessageExtensions.cs
src/Transport/Receiving/MessagePump.cs

Fix legacy compatibility

---

src/AcceptanceTests/Receiving/When_receiving_a_message_from_legacy_asb.cs
src/Transport/Receiving/MessageExtensions.cs
src/Transport/Receiving/MessagePump.cs

Fix legacy compatibility backport

---

src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Transport/AzureServiceBusTransportSettingsExtensions.cs
src/Transport/Testing/TestableCustomizeNativeMessageExtensions.cs
src/Transport/obsoletes-v3.cs

Restored obsolete APIs which are being removed

Obsolete APIs for next major

---

.github/workflows/ci.yml

update ci for release 1.9

---

src/Transport/Receiving/MessageExtensions.cs

Make the data contract serializer a static to avoid having to recreate the object over and over again

Make serializer a static

---

src/Tests/FakeSender.cs
src/Tests/FakeServiceBusClient.cs
src/Tests/Sending/MessageDispatcherTests.cs
src/Transport/Sending/MessageDispatcher.cs

Better error message for the changes introduced in https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/644

Improve batching error message and add test

---

src/Custom.Build.props
src/Directory.Build.props

Similar to #672 for the release branch

Move LangVersion into custom build props

---

src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj

Dual target command line

---

src/CommandLine/Program.cs
src/CommandLine/Topic.cs
src/CommandLineTests/CommandLineTests.cs

Command Line - Assign a default topic name

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/CommandLine/Program.cs
src/CommandLine/Topic.cs
src/CommandLineTests/CommandLineTests.cs
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/Transport/Receiving/MessagePump.cs
src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/750
- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/761
- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/760

Ports recent improvements to 3.1.3

---

src/Transport/Receiving/MessagePump.cs
src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs

Porting back:
- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/750

Slow down processing attempts when circuit breaker has been triggered to conserve resources

---

.github/workflows/ci.yml

Raised https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/808 to keep track of this

Workaround to Azure az CLI bug

---

src/Tests/Sending/MessageDispatcherTests.cs
src/Transport/AzureServiceBusTransportTransaction.cs
src/Transport/Sending/MessageDispatcher.cs

- Backport #842 to release 3.2

Backport 842 to release 3.2

---

src/Transport/Sending/MessageDispatcher.cs

This change satisfies the new `IDE0028` analyzer rules in the .NET 8 SDK.

Use C# 12 collection expressions

---

src/Transport/Sending/MessageDispatcher.cs

Update exception message for oversized batches with more context

---

src/Transport/Sending/MessageDispatcher.cs

relates to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/980 and https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/981

further tweaks to max message size exception message

---

README.md
src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/When_using_token_credential_with_fully_qualified_namespace.cs

DefaultCredential acceptance tests

---

.component-package.yml
.component_package.yml
src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj

This PR adds  a metadata file to the repo that specifies the component packages that are generated as part of the assets in release work flow

Add  metadata component package yml

---

.component-package.yml
src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj

Reverts Particular/NServiceBus.Transport.AzureServiceBus#999
Reverting this PR as component packages that are generated as part of the assets in release work flow will be read from centralized file

Revert "Add  metadata component package yml"

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

upgrade to Azure.Messaging.ServiceBus version that limits batch TryAdd when size limit is reached

---

src/Tests/Sending/MessageDispatcherTests.cs
src/Transport/Sending/MessageDispatcher.cs

Backport of #1019 for the 4.1 branch

Fallback to individual sends when batching is not possible

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Receiving/When_publishing_from_different_topics.cs
src/AcceptanceTests/Receiving/When_publishing_sendonly_and_subscribing_on_different_topics.cs
src/AcceptanceTests/Sending/When_batching_multiple_outgoing_small_messages.cs
src/AcceptanceTests/TestIndependenceSkipBehavior.cs
src/AcceptanceTests/When_operating_with_least_privilege.cs
src/AcceptanceTests/When_using_token_credential_with_fully_qualified_namespace.cs
src/CommandLineTests/CommandLineTests.cs
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/AzureServiceBusTransportTests.cs
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/Tests/Receiving/MessagePumpTests.cs
src/Tests/Sending/MessageDispatcherTests.cs
src/Tests/Sending/MessageRegistryTests.cs
src/Tests/Testing/TestableCustomizeNativeMessageExtensionsTests.cs
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
src/TransportTests/When_MessageLockLostException_is_thrown_from_on_error.cs
src/TransportTests/When_ServiceBusTimeoutException_is_thrown_from_on_error.cs

This PR contains all changes related to assertion model according to the [constraint assertion model](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html).
Using a script, we apply all [assertion rules](https://docs.nunit.org/articles/nunit-analyzers/NUnit-Analyzers.html#assertion-rules-nunit2001---) provided by the NUnit.Analyzers package. In addition, some manual interventions are done when applicable.

Migrate NUnit assertions to the constraint model in preparation of the NUnit 4 upgrade

---

src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.

Upgrading to NUnit4 including all required dependencies

---

src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Exclude some transport tests

---

src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/Receiving/MessagePump.cs

Backport of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1120 for the release-4.0 branch

Transport pump stop for release 4.0

---

src/Transport/AzureServiceBusTransportInfrastructure.cs
src/Transport/Receiving/MessagePump.cs

Backport of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1120 for the release-3.2 branch

Transport pump stop for release 3.2

---

src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/CommandLineTests/CommandLineTests.cs

Port of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1146

Adds roll forward behavior to the command line tool - master

---

src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
src/CommandLineTests/CommandLineTests.cs

Port of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1146

Adds roll forward behavior to the command line tool - release-4.2

---

src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Tests/EventRouting/MigrationTopologyTests.cs
src/Tests/EventRouting/TopicPerEventTopologyTests.cs
src/Transport/EventRouting/MigrationTopology.cs
src/Transport/EventRouting/TopicPerEventTopology.cs
src/Transport/EventRouting/TopicTopology.cs
src/Transport/EventRouting/TopologyOptionsDisableValidationValidator.cs

Follow through on https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1112

Simplify validation and make it possible to opt-out from it

---

src/Transport/EventRouting/SubscriptionManagerCreationOptions.cs

Follow through on https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1112

Address creation option todos

---

src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Transport/EventRouting/MigrationTopology.cs
src/Transport/EventRouting/MigrationTopologyOptions.cs
src/Transport/EventRouting/MigrationTopologyOptionsValidator.cs
src/Transport/EventRouting/TopicTopology.cs

Follow through on https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1112

Obsolete migration topology

---

src/CommandLine/MigrationTopologyEndpoint.cs
src/CommandLine/Subscription.cs
src/CommandLine/TopicPerEventTopologyEndpoint.cs
src/CommandLineTests/CommandLineTests.cs

TopicPerEventType operation tool subscription requires true filter

---

src/CommandLine/MigrationTopologyEndpoint.cs
src/CommandLine/Subscription.cs
src/CommandLine/TopicPerEventTopologyEndpoint.cs
src/CommandLineTests/CommandLineTests.cs

Backport of #1188 to `release-5.0`

TopicPerEventType operation tool subscription requires true filter (#1188)

---

src/Transport/Receiving/MessagePump.cs

The variable is currently labeled `messageId`, but gets put into the context bag as `nativeMessageId`. This change makes the naming more consistent.

Update the name of the variable in the MessagePump

---

src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj

Related to #1212 and #1042 as well as #1041

Re-enable some of the previously excluded transport tests

---

src/AcceptanceTests/When_loading_from_options.cs
src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/Tests/EventRouting/TopicPerEventTopologyTests.cs
src/Transport/EventRouting/EntityValidator.cs
src/Transport/EventRouting/MigrationTopologyOptions.cs
src/Transport/EventRouting/TopicPerEventTopology.cs
src/Transport/EventRouting/TopologyOptions.cs

Backport of #1242 for the 5.1 branch

Fail Fast on Missing Topic Mapping in PublishedEventToTopicsMap for Topic-Per-Event Topology
