- src/Transport/Receiving/MessagePump.cs
When recoverability throws an exception, we shouldn't lock an incoming message for the `maxLockDuration` time and instead safely abandon it. This was caught by one of the TransportTests (`Should_reinvoke_on_error_with_original_exception`)
> Safe abandon incoming message when recoverability is throwing

- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/TransactionScopeSuppressFeature.cs
Anyone using multi-endpoint host with Azure Service Bus .NET Standard transport and a transport supporing `TransactionScope` [transport transaction](https://docs.particular.net/transports/transactions).
Azure Service Bus .NET Standard transport suppresses transaction scope for all transports in multi-endpoint host.
---
Replaces PR #11
> Do not auto-activate TransactionScopeSuppressFeature

- src/Transport/Receiving/MessagePump.cs
@tmasternak and I have been trying to hunt down an issue with ServiceControl AcceptanceTests and stumbled over the shutdown read of `numberOfExecutingReceives`. It would not hurt to properly read it with Interlocked since the value is increased and decremented.
> Interlocked.Read numberOfExecutingReceives

- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- Update ASB client to 3.2.0 (supports multi-targeting)
- Introduce `System.ValueTuple` for `net461`
- Update Particular.Packaging to remove warning about licenceUrl
> Bump ASB client to 3.2.0 (multi-targeting)

- src/Transport/Configuration/AzureServiceBusTransportSettingsExtensions.cs
Fixes #49 
Zero is the default value for ASB client.
NServiceBus transport sets the value to zero if user does not specify anything, but does not allow configuring prefetch count to zero using the API.
This PR fixes the API to accept zero as a valid value.
> Allow PrefetchCount to be set to zero

- src/CommandLine/CommandRunner.cs
- src/CommandLine/Endpoint.cs
- src/CommandLine/Program.cs
- src/CommandLine/Rule.cs
- src/CommandLine/Topic.cs
- src/CommandLineTests/CommandLineTests.cs
Closes https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/67
Documentation https://github.com/Particular/docs.particular.net/pull/4422
> Allow rule creation

- src/Transport/Receiving/MessagePump.cs
- src/TransportTests/When_MessageLockLostException_is_thrown.cs
- src/TransportTests/When_ServiceBusTimeoutException_is_thrown.cs
Backport of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/70 for release-1.2 branch
> MessageLockLostException should not trigger critical errors

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/Transport/Sending/MessageSenderPool.cs
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
Just curious what breaks
**Update**
- Updated to new major 4.0.0
- Updated to new minor 4.1.0 with bug fixes
- Updated to new patch 4.1.1 with bug fixes
> Bump SDK to latest

- src/AcceptanceTests/Receiving/When_receiving_a_message.cs
- src/Transport/Receiving/MessagePump.cs
_Fixes #86_
_Replaces https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/85_
Propagate `Microsoft.Azure.ServiceBus.Message` via message's `ContextBag` to provide the information set by the broker per message.
An example is to allow the cancellation of an incoming message that cannot be processed due to expired lock. The system property, `LockedUntilUtc` could help to decide wherever a message should be attempted for processing or not in case it spent time longer than `MaxLockDuration` while in prefetch. 
With this change, the decision wherever a message should or should not be processed can be made at any point where context is available. E.g. a custom behaviour and `TransportReceiveContext.AbortReceiveOperation()` API, message handler, etc.
> Expose native Message

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/Sending/MessageSenderPoolTests.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Configuration/AzureServiceBusTransportSettingsExtensions.cs
- src/Transport/Configuration/SettingsKeys.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Sending/MessageSenderPool.cs
Add support for custom retry policy via configuration API.
This adds a capability that was also available with the legacy ASB transport, [overriding RetryPolicy](https://docs.particular.net/transports/azure-service-bus/legacy/configuration/full#controlling-connectivity-messaging-factories) via configuration API.
> Add support for custom retry policy

- src/Custom.Build.props
The target is no longer needed now that it's been added to Particular.Packaging, and since there's nothing else in the file, I've removed it entirely.
> Remove Custom.Build.props

- src/Transport/Receiving/TransactionScopeSuppressBehavior.cs
See https://github.com/Particular/NServiceBus/pull/4125
- `Behavior<TContext>`is no longer used. Internal behaviors directly implement `IBehavior<TIn, TOut>`which saves a display class allocation and a function delegate allocation
```
public Task Invoke(TContext context, Func<TContext, Task> next)
{
Behavior<TContext>.\u003C\u003Ec__DisplayClass0_0 cDisplayClass00 = new Behavior<TContext>.\u003C\u003Ec__DisplayClass0_0();
cDisplayClass00.next = next;
cDisplayClass00.context = context;
Guard.AgainstNull(nameof (context), (object) cDisplayClass00.context);
Guard.AgainstNull(nameof (next), (object) cDisplayClass00.next);
// ISSUE: method pointer
return this.Invoke(cDisplayClass00.context, new Func<Task>((object) cDisplayClass00, __methodptr(\u003CInvoke\u003Eb__0)));
}
```
> Switch to IBehavior because for internal things it is better in terms of allocations

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
Backport of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/195 to `release-1.5`
> Support for Microsoft.Azure.ServiceBus 5.0 version range

- src/AcceptanceTests/Receiving/When_customizing_an_outgoing_native_message.cs
- src/AcceptanceTests/Sending/When_customizing_an_outgoing_native_message.cs
- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Sending/CustomizeNativeMessageExtensions.cs
- src/Transport/Sending/MessageDispatcher.cs
- src/Transport/Sending/NativeMessageCustomizer.cs
> Allow outgoing message customizations

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
Bugfix - Fixing a bug in management client that is sending atom XML elements out of order PR [16488](https://github.com/Azure/azure-sdk-for-net/pull/16488)
Bugfix - Convert "Invalid operation while the connection is closing" to retriable ServiceBusException PR [17023](https://github.com/Azure/azure-sdk-for-net/pull/17023)
> Update SDK to 5.1.0

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/Sending/CustomizeNativeMessageExtensions.cs
- src/Transport/obsoletes-v2.cs
This overload was just removed instead of being properly obsoleted. Therefore this PR adds the overload back and adds an obsolete method.
> Obsolete CustomizeNativeMessage method

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/TestSuiteConstraints.cs
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/Transport/Receiving/MessagePump.cs
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
main differences seem to be related to work from the cancellation token source TF, changing some types and removing the cancellation token on the `MessageContext`.
> Update to latest version of core

- src/CommandLine/Endpoint.cs
- src/CommandLine/Program.cs
- src/CommandLineTests/CommandLineTests.cs
Closes https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/173.
* were fixed names in the output for some entities
before the change:
and after:
> Skip throwing an exception when a queue already exists.

- src/Transport/Administration/NamespacePermissions.cs
- src/Transport/Administration/SubscriptionManager.cs
The transport calls `NamespacePermissions.CheckPermission()` multiple times, at startup and runtime (e.g. when creating queues, when creating the subscription, and when subscribing/unsubscribing). Given it's always the same check, it seems to be a lot more efficient to check this once and cache the result (what the subscription manager itself already did).
With this change, we can save some HTTP requests at startup time, improving startup performance.
I've used a `Lazy<Task>` for caching. I think it's not necessary to wrap the call in the factory in a `Task.Run` as usually seen in guidance for async-lazy types as this involves IO that is always going to be awaited directly, so fast returns from the factory method are not that important (there is also no parallelism involved at startup) …
> Cache namespace permission check results

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Tests/Testing/TestableCustomizeNativeMessageExtensionsTests.cs
- src/Transport/Testing/TestableCustomizeNativeMessageExtensions.cs
Addresses #218
Bringing these changes back to 1.9 requires a few changes to the code here since `master` behaves slightly different when it comes to storing the customizations
> Implement testing helpers to get access to the customization

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/MigrationApiTests.cs
- src/Transport/AzureServiceBusSettings.cs
- src/Transport/AzureServiceBusSettingsExtensions.cs
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/obsoletes-v2.cs
Added the shim API to ease migration. This included special handling to also support the `ConnectionString` extension instead of having to provide it via the ctor.
> Add Core v7 shim configuration API

- .github/workflows/release.yml
This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.
> Use Key Vault certificate for signing - release-1.9

- .github/workflows/release.yml
This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.
> Use Key Vault certificate for signing - release-1.8

- src/AcceptanceTests/TestIndependenceSkipBehavior.cs
Same change as made in the legacy ASB transport (https://github.com/Particular/NServiceBus.AzureServiceBus/pull/1011) in order to make the new acceptance tests introduced with #366 pass.
> Only discard messages with mismatching TestRunId

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/AzureFunctionsDownstreamApiTests.cs
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/obsoletes-v2.cs
Changes proposed for https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/287#discussion_r696379546
Summary:
- Make parameterless constructor protected
- Make ConnectionString property protected
> Proposed API changes needed for Azure Functions

- .github/workflows/ci.yml
There are several flaky tests when the suite is run among multiple frameworks, which is why none of the other PRs in this repo currently pass CI. Rather than fight it, just run each framework separately and benefit from 20m CI times instead of 45m.
> setup-azureservicebus-action

- src/Transport/Receiving/MessagePump.cs
In the logs of some failing tests, we've seen error messages thrown from `AbandonMessageAsync` because this doesn't take into account scenarios running on transaction mode `None` correctly and therefore run into the following error:
```
Error NServiceBus.Transport.AzureServiceBus.MessagePump: Error receiving messages. System.InvalidOperationException: The operation is only supported in 'PeekLock' receive mode.
at Azure.Messaging.ServiceBus.ServiceBusReceiver.ThrowIfNotPeekLockMode()
at Azure.Messaging.ServiceBus.ServiceBusReceiver.AbandonMessageAsync(Guid lockToken, IDictionary`2 propertiesToModify, CancellationToken cancellationToken)
at Azure.Messaging.ServiceBus.ServiceBusReceiver.AbandonMessageAsync(ServiceBusReceivedMessage message, IDictionary`2 propertiesToModify, CancellationToken …
```
> Switch to SafeAbandonMessageAsync

- src/TransportTests/When_MessageLockLostException_is_thrown_from_on_error.cs
- src/TransportTests/When_ServiceBusTimeoutException_is_thrown_from_on_error.cs
These tests occasionally fail (see https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/actions/runs/1934833391) because `SetResult` might be called multiple times, making the `onError` throwback behave differently:
1. message arrives and throws an exception in `onMessage`
2. invoke `onError`
3. `onError` calls `SetResult(true)`
4. `onError` throws `ServiceBusException`
5. internal exception handling calls `AbandonMessage`
6. Message is received again
7. exception thrown in `onMessage`
8. `onError is invoked again`
9. `onError` calls `SetResult(true)` and now throws an `InvalidOperationException` instead
10. The message pump exception handling invokes the critical error action since this in not an expected exception.
> Use TrySetResult instead of SetResult

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/Receiving/MessagePump.cs
Builds on top of #639 
Exposes the `MaxAutoLockRenewalDuration` from the SDK and forwards that to the `ServiceBusProcessor` used in the message pump. The processor will continue to extend the message lock up to the specified time.
The SDK itself uses a default value of 5 minutes. I did only expose that fact over the documentation, but not hard-code the 5 minutes into the code. This makes sure we follow the same defaults as the underlying SDK. Another option would be to remove the remark entirely and just rely on the SDK defaults without mentioning on the documentation.
It is also possible to manually extend the lock in the message handling pipeline by getting access to the processor arguments available on the context (introduced in the referenced PR).
> Expose the MaxAutoLockRenewalDuration

- src/Tests/FakeSender.cs
- src/Tests/FakeServiceBusClient.cs
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Sending/MessageSenderRegistry.cs
Additional enhancements as a follow-up to #644 
- Makes sure all senders are properly disposed
- Makes sure all clients including the default client are disposed
- Makes sure the default client has never the cross entity transaction flag set to avoid accidentally using the feature where it makes no sense to use it
- Creates dedicated option types for the receivers and the default clients (for better clarity, even though the option type is internally cloned)
- Assigns more descriptive IDs to the various client types
> Client management improvements

- src/CommandLine/CommandRunner.cs
- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLine/Program.cs
- src/CommandLineTests/CommandLineTests.cs
Closes #562 
I have thought about adding tests to verify the credential chain works but ultimately figured it is too complex and not adding much value. Having tests that verify that part of the tool would require either every developer to have additional credentials on the machine or we could conditionally only execute the tests on the CI. For those, the azure/login action would establish the token and we could execute the tests but ultimately, we would only be testing the SDK so I figured it is not worth the complexity.
> Enable the command line tool to use a namespace with DefaultAzureCredentials

- src/Directory.Build.props
- src/Tests/FakeProcessor.cs
- src/Tests/FakeReceiver.cs
- src/Tests/FakeServiceBusClient.cs
- src/Tests/Receiving/MessagePumpTests.cs
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
Brings in some test coverage for some of the scenarios of the pump. Not everything is covered, and there is still some redundancy that I deliberately did not yet remove. With this in place, we hopefully are in a much better state to continue to evolve the pump and add more tests. For example, it is now possible to verify the processor event args are added to the context (which I will add as a subsequent PR).
> Some test coverage for the pump

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/AzureServiceBusTransportSettingsExtensions.cs
- src/Transport/obsoletes-v3.cs
> Make the token credential and the fullyQualifiedNamespace a dedicated connection setting instead of misusing the connection string.

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/AzureServiceBusTransportTransactionExtensions.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/ProcessMessageEventArgsExtensions.cs
Brings the ability to turn the azure service bus transaction into a scope without having to expose the transaction property.
Successfully tested in https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/553/files#diff-c3a09a3104709e83ceea80ee3b45cb50759a17e656370b36f86daada61f8bd1cR221
> Introduce ToTransactionScope as an extension on AzureServiceBusTransportTransaction

- src/Tests/Receiving/MessagePumpTests.cs
- src/Transport/Receiving/MessagePump.cs
Discovered while smoke testing
This makes sure we attempt to abandon the message so that it can reappear on the same consumer. Otherwise they will be stuck it seems
Endpoint1 sends 10 messages
```bash
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
Message1 sent
2022-11-02 14:31:05.274 INFO  Received Message2: Hello from Endpoint2
2022-11-02 14:31:05.274 INFO  Received Message2: Hello from Endpoint2
2022-11-02 14:31:05.284 INFO  Received Message2: Hello from Endpoint2
2022-11-02 14:31:05.872 INFO  Received Message2: Hello from Endpoint2
2022-11-02 14:31:06.607 INFO  Received Message2: Hello from Endpoint2
```
Endpoint2 has set the LockDuration to 30 seconds, concurrency set to 10
```bash
2022-11-02 14:30:19.613 …
```
> Try to abandon the message when the lock expired

- src/Custom.Build.props
- src/Directory.Build.props
[According to the sync](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/671) I should never had added into the `Directory.build.props`. So moving the LangVersion to the custom build props
> Move LangVersion into custom build props

- src/Tests/Receiving/MessagePumpTests.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/MessagePump.cs
Small refactoring to remove some unnecessary dependencies from the `MessagePump` constructor
> Initialize SubscriptionManager outside MessagePump

- src/Transport/AzureServiceBusTransport.cs
> Use the FullyQualifiedNamespace instead of the connection string when the token credential is set

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
The previous version was 7.4.0 and lots of fixes have been released since.
https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.11.1/sdk/servicebus/Azure.Messaging.ServiceBus/CHANGELOG.md
> 📦 Bump Azure.Messaging.ServiceBus to 7.11.1 - release-2.0

- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/Transport/Receiving/MessagePump.cs
This leverages the feature [I contributed to the Azure.Messaging.ServiceBus library](https://github.com/Azure/azure-sdk-for-net/pull/33162/) that was released as part of 7.12.0. With that approach, it is no longer necessary to stop and start the transport. We can now adjust the processor's concurrency and prefetch count. By setting the prefetch count the underlying AMQP link credit is updated automatically if it has changed.
> Switch the transport to use UpdatePrefetchCount on the processor when rate limiting occurs

- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
This is meant to address two issues
- https://github.com/Particular/ServiceControl/issues/2907
- https://github.com/Particular/ServiceControl/issues/3318
by checking the state of the circuit breaker when `Failure` is invoked. If the breaker has already been triggered, the method pauses for 10 seconds (instead of 1 second) to prevent flooding the logs. The issue affects both ServiceControl and regular endpoints.
> Pause longer when circuit breaker has been triggered

- src/AcceptanceTests/Receiving/When_publishing_from_different_topics.cs
- src/AcceptanceTests/Receiving/When_publishing_sendonly_and_subscribing_on_different_topics.cs
- src/AcceptanceTests/When_operating_with_least_privilege.cs
- src/Transport/Administration/NamespacePermissions.cs
- src/Transport/Administration/QueueCreator.cs
- src/Transport/Administration/SubscriptionManager.cs
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
Closes #645 
This PR leverages the rule manager. The rule manager [doesn't support updating rules](https://github.com/Azure/azure-sdk-for-net/issues/31625), so we have to first delete the rules and then create them. It is also not possible to [enumerate rules on subscriptions with forwarding enabled](https://github.com/Azure/azure-sdk-for-net/pull/34816).
> Manage subscriptions without manage rights

- src/Transport/Sending/MessageDispatcher.cs
- Alternative to #839 
Checks for attempts to send more than 100 messages in a single transaction, which is not allowed https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas and throws an exception.
Compared to #839 this PR makes minimal changes to the dispatcher. It iterates through the outgoing transactions only if the total count is high enough to potentially go over th limit, and if we are participating in a transaction.
> Simpler detect oversized batch

- src/Tests/Sending/MessageDispatcherTests.cs
- src/Transport/AzureServiceBusTransportTransaction.cs
- src/Transport/Sending/MessageDispatcher.cs
_Addresses #817_
_Forward ports https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/840 to v3 of the transport_
When sending messages inside a receive transaction, it is possible for some messages to be sent by the dispatcher outside of the transaction, even without using isolated dispatch consistency.
When an endpoint is configured to use SendsAtomicWithReceive transaction mode, and a handler attempts to dispatch more than 100 messages (which is [not supported by the Azure Service bus service](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas)), message processing fails, causing the message to be moved to the error queue. Depending on the number of messages dispatched (the higher, the more risk), the message to the error queue becomes …
> Detect and throw when attempting to send more than 100 messages inside a transaction

- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
Azure.Identity < 1.10.2 is affected by [CVE-2023-36414](https://github.com/advisories/GHSA-5mfx-4wcx-rv27).
This PR updates the version of Azure.Identity used by the `asb-transport` command line (CLI) tool to 1.10.4.
> Update Azure.Identity to non-vulnerable version

- src/Tests/Sending/MessageDispatcherTests.cs
- src/Transport/Sending/MessageDispatcher.cs
After discussions, we have concluded that using the TryAdd capability of the SDK and fall back to using individual sends in cases when the message is too large is to best way to move forward for now instead of introducing a SendOption extension that allows to selectively opt out from batching per message.
The first `TryAdd` can only fail when the message is too large. Subsequent `TryAdd` attempt to add as much as possible until it returns false (either too large or batch full) then the current batch is sent, a new one is created and the message is attempted to add again. If the batch was full before, but the message fits in, it will be added. Otherwise, it will be pulled out for individual sends and batching continues (see comment in code)
> Fallback to individual sends when batching is not possible

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_message_visibility_expired.cs
- src/Tests/FakeProcessor.cs
- src/Tests/FakeReceiver.cs
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Tests/Receiving/MessagePumpTests.cs
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/ProcessMessageEventArgsExtensions.cs
- src/Transport/Utilities/TransactionExtensions.cs
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
This PR follows through on related changes done in [Amazon SQS](https://github.com/Particular/NServiceBus.AmazonSQS/pull/1861) but adjusts the core pieces of the change to Azure Service Bus-specific behavior. Additionally, it brings in a number of layered tests that verify the code works as expected and doesn't accidentally break later.
An LRU cache to track the delivery attempts is not necessary because the receive count is automatically updated by the storage queue infrastructure.
The changes have only been applied for the **receive only** transaction mode because with the sends-atomic receive mode the outgoing messages are enlisted with a send-via information together with the incoming message. The outgoing messages are only sent when the incoming message successfully completed. In …
> Track messages that successfully completed the message or error pipeline but failed to get acknowledged due to expired leases in receiveonly mode

- src/Tests/FakeSender.cs
- src/Transport/Sending/MessageDispatcher.cs
Fixes #1048
[Previous test run of first commit before rebase that reproduced the problem](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/actions/runs/11017750455)
I think as a follow-up PR for master it might make sense to tone down slightly the overly clever trickery that fell apart when we introduced the collecting of too large messages, but I figured these structural changes should be done outside the realm of fixing the bug.
> Inline dispatching of individual sends for messages that are too large to fit into a batch

- src/AcceptanceTests/NServiceBus.Transport.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_message_visibility_expired.cs
- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/NServiceBus.Transport.AzureServiceBus.CommandLine.Tests.csproj
- src/Tests/FakeProcessor.cs
- src/Tests/FakeReceiver.cs
- src/Tests/NServiceBus.Transport.AzureServiceBus.Tests.csproj
- src/Tests/Receiving/MessagePumpTests.cs
- src/Transport/NServiceBus.Transport.AzureServiceBus.csproj
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/ProcessMessageEventArgsExtensions.cs
- src/Transport/Utilities/TransactionExtensions.cs
- src/TransportTests/NServiceBus.Transport.AzureServiceBus.TransportTests.csproj
Backport of #1034 to `release-4.0`
> Track messages that successfully completed the message or error pipeline but failed to get acknowledged due to expired leases in receiveonly mode 

- src/Tests/FakeSender.cs
- src/Transport/Sending/MessageDispatcher.cs
Follow through on #1049 
This attempts to simplify the dispatcher a bit where possible to no longer rely on the synchronous path. This PR attempts to find a good balance between allocating the necessary task lists with the number of items needed because that is beneficial compared to doing `Task.WhenAll` with `Select` and `ToArray`
During the discussion with @andreasohlund and @PhilBastian we concluded the original problem would only really have been discovered if the following are true:
- Premium namespace (we don't use a premium namespace yet in our CI/CD environment)
- The underlying SDK cannot yet have cached the batch size information of the underlying AMQP link (will make the `CreateMessageBatchAsync` yield) or the large message has to be put into a batch that is sent after the …
> Simplify dispatcher

- src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
This implementation simplifies the implementation of the circuit breaker by no longer incrementing the failure count. The circuit breaker doesn't really care about the number of failures. It cares about tracking the potential state transitions between `Armed`, `Disarmed` and `Triggered`.
By focusing the implementation on these state transitions, the complex interaction between the `failureCount` and the `triggered` flag can be removed and replaced by a state that has meaningful names.
> Address races in the repeated failure circuit breaker by introducing explicit state transitions

- src/Tests/Receiving/RepeatedFailuresOverTimeCircuitBreakerTests.cs
- src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
Serializing the arm/disarm actions is not enough. The state transition preceding the arm/disarm action must be captured in the lock as well, otherwise the state transitions could happen properly but then the arm/disarm actions could be executed by the processor in the wrong order, leaving the logic of the circuit breaker itself intact but the consequences of the arm/disarm actions in an incorrect state.
I also added xdoc as a way to document that the arm/disarm actions are called within a lock, and to maybe pave the way for this to be used as a shared component.
> Use locks to serialize arm/disarm actions

- src/Tests/Receiving/RepeatedFailuresOverTimeCircuitBreakerTests.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
* Backports the following fixes to release branch `release-2.0` to be released as version 2.0.8. While this version was not directly affected by https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/1063, these fixes were pre-emptively backported to prevent other circuit-breaker-releated bugs that may exist:
* https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1066
> Backport of circuit breaker fixes involved in bug in later versions

- src/Tests/Receiving/RepeatedFailuresOverTimeCircuitBreakerTests.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
* Fixes https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/1063 in version `3.2.5`. by backporting the following to release branch `release-3.2`:
* https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1058
* https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1066
> Receive failures lock transport into single concurrency mode

- src/AcceptanceTests/When_customizing_outgoing_messages.cs
- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/OutgoingNativeMessageCustomizationAction.cs
- src/Transport/Sending/MessageDispatcher.cs
- src/Transport/Sending/NativeMessageCustomizationBehavior.cs
Replaces:
- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1071
Added the ability to customize then native message type just before it is dispatched to Azure Service Bus and gets access to [IOutgoingTransportOperation](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/IOutgoingTransportOperation.cs).
```c#
var transport = new AzureServiceBusTransport(connectionstring);
//...
transport.OutgoingNativeMessageCustomization = (outgoingoperation, servicebusmessage) => { servicebusmessage.ContentType = "text/xml" };
```
or
```c#
public Task MyCustomizer(IOutgoingTransportOperation message, ServiceBusMessage nativeMessage)
{
}
var transport = new AzureServiceBusTransport(connectionstring);
//... …
```
> Allow customizing outgoing native ServiceBusMessage

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/Sending/OutgoingMessageExtensionsFixture.cs
- src/Transport/AzureServiceBusTransport.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/AzureServiceBusTransportSettingsExtensions.cs
- src/Transport/Sending/MessageDispatcher.cs
- src/Transport/Sending/OutgoingMessageExtensions.cs
Add operation extension to not generate legacy `NServiceBus.Transport.Encoding` header in native custom properties / ApplicationProperties
> Ability to not generate legacy `NServiceBus.Transport.Encoding` header

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/MessagePump.cs
- src/Transport/Receiving/QueueAddressQualifier.cs
- src/TransportTests/ConfigureAzureServiceBusTransportInfrastructure.cs
- src/TransportTests/When_using_dlq_qualifier.cs
Support reading from dead-letter queues with transport seam:
Create `ReceiveSettings` with property key `Azure.Messaging.ServiceBus.SubQueue` and the value to match `DeadLetter`:
```c#
var queueProperties = new Dictionary<string, string>(1);
queueProperties[typeof(SubQueue).FullName] = SubQueue.DeadLetter.ToString();
var receiveSettings = new ReceiveSettings(
id: inputQueue,
receiveAddress: new QueueAddress(inputQueue, properties: queueProperties),
usePublishSubscribe: false,
purgeOnStartup: false,
errorQueue: errorQueue
```
> Support reading from dead-letter queues with transport seam

- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/MessagePump.cs
This aligns the transport to stop the pumps on transport shutdown and at the same time makes sure the pumps stop method can be called multiple times. 
This is part of addressing some low-hanging fruit to align all transports for the transport seam usage scenarios to make sure pumps are stopped when the transport shuts down. 
I have tried to write a transport test for it to enforce it eventually for all transport but couldn't find a way to do that without introducing flags on the transport interface and using fancy techniques like default members which seams overkill
> Stop pumps on shutdown

- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/MessagePump.cs
When a transport is shutting down, it should be able to dispose all internal resources that it created.
All pumps are stopped by the transport.
The receiving pumps need to be stopped manually after shutdown.
All supported versions
N/A
> Not all internal resources are disposed before shutting down

- src/CommandLine/NServiceBus.Transport.AzureServiceBus.CommandLine.csproj
- src/CommandLineTests/CommandLineTests.cs
The absence of .Net 7 on the Github runner is breaking the build pipeline. 
.Net 7 was added on https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/759
This change makes the command line tool single target, but sets the roll forward behavior to `Major` and adds the target framework to the command that the tests execute.
> Update the command line tool to not use .Net 7

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Transport/EventRouting/TopicPerEventTopology.cs
While writing the documentation for interface based inheritance I realized I have to write
```csharp
topology.SubscribeTo<IOrderStatusChanged>("Shipping.OrderStatusChanged");
```
even when I have the contracts available instead of 
```csharp
topology.SubscribeTo<IOrderStatusChanged, OrderStatusChanged>();
```
> Introduce subscribe overloads that allow mapping to implementation type using the default convention

- src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/Tests/EventRouting/SubscribeEventToTopicsMapConverterTests.cs
- src/Transport/EventRouting/MigrationTopologyOptions.cs
- src/Transport/EventRouting/TopologyOptions.cs
Adds handling of cases when a property was not included in the json document. Also adds more tests for some corner cases e.g.
- Type annotation not provided
- Type annotation pointing to migration topology
- Properties missing from json
> Fix minor issues with deserialization

- src/Tests/Sending/MessageDispatcherTests.cs
- src/Tests/Sending/MessageRegistryTests.cs
- src/Transport/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Sending/MessageDispatcher.cs
- src/Transport/Sending/MessageSenderRegistry.cs
Addresses:
- #1141 
In order to provide additional context to connectivity exceptions to ASB, the `MessageDispatcher` class needs access to the `ServiceBusClient` instance that was used to connect, so it can determine whether TCP or WebSockets was used.  For this reason, the default `ServiceBusClient` instance is provided to the `MessageDispatcher` class instead of `MessageSenderRegistry`, and it is the `MessageDispatcher` that coalesces any null client parameter to the default client.
> Improve exception messages for connectivity exceptions
